### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by hector-munachi** [kt946/japanese-quiz-mern-app#4]
I was just curious how you went about deploying the application with a client and server in one app?

**Comment by kt946** [comment]
So for this app, I was able to deploy it through Heroku and Render.

For Heroku, I used the Heroku CLI to push the main branch of the repository to Heroku. While the web app was building, I made sure to add any environment variables in Settings and then Config Vars. The process to install the dependencies, build the app, and launch it should be done automatically on Heroku's end. The package.json in the main directory of the app should contain the "start", "dev", "install", and "build" scripts. Those are important as Heroku will execute those scripts when building the application, particularly the "install" and "build" scripts.

For Render, the process is a bit different.

On Render's dashboard, I created a new web service project and linked it to the Github repository. After adding the environment variables, I navigated to the Settings tab and had to manually input the build commands into the Build & Deploy form. 

The Build Command field would be: 
```
cd server && npm i && cd ../client && npm i && npm run build
```
The Start Command field would be:
```
npm start
```

At least for me, this took some trial and error to get the build process to finish without any errors. Most of my experience comes from my bootcamp. I hope I answered your question. 👍
